# Do not automatically trigger
trigger: none
pr: none

variables:
  sourceBranch: master
  sourcePipelineId: 1
  sourceProjectName: EmsApi.Client
  githubServiceConnection: ge-flight-analytics-pat
  nugetServiceConnection: nuget-public

jobs:

- deployment: github
  displayName: GitHub.com
  pool:
    vmImage: windows-latest
  environment: github
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: DownloadPipelineArtifact@2
          displayName: Download artifacts
          inputs:
            source: specific
            project: $(sourceProjectName)
            pipeline: $(sourcePipelineId)
            runVersion: latestFromBranch
            runBranch: refs/heads/$(sourceBranch)
            path: $(Build.ArtifactStagingDirectory)

        - pwsh: |
            $versionFile = Get-Content "src/Directory.Build.props"
            $exp = "<VersionPrefix>(?<version>[\d]\.[\d]\.[\d])<\/VersionPrefix>"
            $matchInfo = $versionFile | Select-String $exp
            if( -not $matchInfo.Matches.Success ) {
              throw "The regular expression $exp did not match anything in the Directory.Build.props file."
            }
            
            $version = $matchInfo.Matches.Groups | Where Name -eq "version" | Select-Object -ExpandProperty Value
            Write-Host "##vso[task.setvariable variable=releaseVersion]$version"
          displayName: Determine tag

        - task: GitHubRelease@0
          displayName: Create GitHub release
          inputs:
            gitHubConnection: $(githubServiceConnection)
            tagSource: manual
            tag: v$(releaseVersion)
            title: Version $(releaseVersion)
            releaseNotesFile: ReleaseNotes.md
            assets: $(Build.ArtifactStagingDirectory)/drop/*

- deployment: nuget
  displayName: NuGet.org
  pool:
    vmImage: windows-latest
  environment: nuget
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none

        - task: DownloadPipelineArtifact@2
          displayName: Download artifacts
          inputs:
            source: specific
            project: $(sourceProjectName)
            pipeline: $(sourcePipelineId)
            runVersion: latestFromBranch
            runBranch: refs/heads/$(sourceBranch)
            path: $(Build.ArtifactStagingDirectory)

        - task: NuGetCommand@2
          displayName: Push to NuGet.org
          inputs:
            command: push
            packagesToPush: $(Build.ArtifactStagingDirectory)/drop/*.nupkg
            nuGetFeedType: external
            publishFeedCredentials: $(nugetServiceConnection)